/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/***************************************************************
* file: NewJFrame1.java
* author: A. Wang
* class: CS 245 Programming Graphical User Interfaces
*
* assignment: checkpoint 1.0
* date last modified: 8/9/2016
*
* purpose: This program creates the hangman game to be played with the answer
* nurse.
*
****************************************************************/ 
import java.util.Calendar;
import java.util.GregorianCalendar;
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        A1 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        D1 = new javax.swing.JToggleButton();
        E1 = new javax.swing.JToggleButton();
        F1 = new javax.swing.JToggleButton();
        G1 = new javax.swing.JToggleButton();
        H1 = new javax.swing.JToggleButton();
        I1 = new javax.swing.JToggleButton();
        J1 = new javax.swing.JToggleButton();
        K1 = new javax.swing.JToggleButton();
        L1 = new javax.swing.JToggleButton();
        M1 = new javax.swing.JToggleButton();
        N1 = new javax.swing.JToggleButton();
        O1 = new javax.swing.JToggleButton();
        P1 = new javax.swing.JToggleButton();
        Q1 = new javax.swing.JToggleButton();
        R1 = new javax.swing.JToggleButton();
        S1 = new javax.swing.JToggleButton();
        T1 = new javax.swing.JToggleButton();
        U1 = new javax.swing.JToggleButton();
        V1 = new javax.swing.JToggleButton();
        W1 = new javax.swing.JToggleButton();
        X1 = new javax.swing.JToggleButton();
        Y1 = new javax.swing.JToggleButton();
        Z1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nurse = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("Score: " + score);
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lLeg = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        rLeg = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        chest = new javax.swing.JLabel();
        left = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        A1.setText("A");
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });

        B1.setText("B");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });

        C1.setText("C");
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });

        D1.setText("D");
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });

        E1.setText("E");
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });

        F1.setText("F");
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1MouseClicked(evt);
            }
        });

        G1.setText("G");
        G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G1MouseClicked(evt);
            }
        });

        H1.setText("H");
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H1MouseClicked(evt);
            }
        });

        I1.setText("I");
        I1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                I1MouseClicked(evt);
            }
        });

        J1.setText("J");
        J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J1MouseClicked(evt);
            }
        });

        K1.setText("K");
        K1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                K1MouseClicked(evt);
            }
        });

        L1.setText("L");
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
        });

        M1.setText("M");
        M1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M1MouseClicked(evt);
            }
        });

        N1.setText("N");
        N1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N1MouseClicked(evt);
            }
        });

        O1.setText("O");
        O1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                O1MouseClicked(evt);
            }
        });

        P1.setText("P");
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1MouseClicked(evt);
            }
        });

        Q1.setText("Q");
        Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1MouseClicked(evt);
            }
        });

        R1.setText("R");
        R1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R1MouseClicked(evt);
            }
        });

        S1.setText("S");
        S1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S1MouseClicked(evt);
            }
        });

        T1.setText("T");
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T1MouseClicked(evt);
            }
        });

        U1.setText("U");
        U1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U1MouseClicked(evt);
            }
        });

        V1.setText("V");
        V1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V1MouseClicked(evt);
            }
        });

        W1.setText("W");
        W1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W1MouseClicked(evt);
            }
        });

        X1.setText("X");
        X1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X1MouseClicked(evt);
            }
        });

        Y1.setText("Y");
        Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Y1MouseClicked(evt);
            }
        });

        Z1.setText("Z");
        Z1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Z1MouseClicked(evt);
            }
        });

        jButton1.setText("Skip");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Skip1(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Alibi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Hangman");

        Nurse.setText("___    ___    ___    ___    ___");

        jTextField1.setFocusable(false);

        jTextField2.setFocusable(false);
        new Thread(){
            public void run(){
                while (timeRun == 0){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    String time = month+1 + "/" + day + "/" + year + " " + hour + ":" + min + ":" + sec + " ";
                    jTextField2.setText(time);
                }
            }
        }.start();

        jLabel3.setText("  n  ");
        jLabel3.setVisible(false);

        jLabel4.setText("  u  ");
        jLabel4.setVisible(false);

        jLabel5.setText("  r  ");
        jLabel5.setVisible(false);

        jLabel6.setText("  s  ");
        jLabel6.setVisible(false);

        jLabel7.setText("  e  ");
        jLabel7.setVisible(false);

        lLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLeg.setText("/");
        lLeg.setVisible(false);

        right.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        right.setText("\\");
            right.setVisible(false);

            rLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            rLeg.setText("\\");
                rLeg.setVisible(false);

                head.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
                head.setText("O");
                head.setVisible(false);

                chest.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
                chest.setText(" l");
                chest.setVisible(false);

                left.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                left.setText("/");
                left.setVisible(false);

                jLayeredPane1.setLayer(lLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(right, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(rLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(head, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(chest, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(left, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
                jLayeredPane1.setLayout(jLayeredPane1Layout);
                jLayeredPane1Layout.setHorizontalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rLeg))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(head)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(right)))
                        .addContainerGap())
                );
                jLayeredPane1Layout.setVerticalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(head)
                        .addGap(1, 1, 1)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chest)
                            .addComponent(right)
                            .addComponent(left))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLeg)
                            .addComponent(rLeg))
                        .addContainerGap())
                );

                jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel12.setText("|");

                jLabel13.setText("_____________");

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(N1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(O1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(W1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Y1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Z1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nurse)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(F1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(I1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(J1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(K1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(M1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1)
                        .addComponent(Nurse)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A1)
                            .addComponent(B1)
                            .addComponent(C1)
                            .addComponent(D1)
                            .addComponent(E1)
                            .addComponent(F1)
                            .addComponent(G1)
                            .addComponent(H1)
                            .addComponent(I1)
                            .addComponent(J1)
                            .addComponent(K1)
                            .addComponent(L1)
                            .addComponent(M1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(N1)
                            .addComponent(O1)
                            .addComponent(P1)
                            .addComponent(Q1)
                            .addComponent(R1)
                            .addComponent(S1)
                            .addComponent(T1)
                            .addComponent(U1)
                            .addComponent(V1)
                            .addComponent(W1)
                            .addComponent(X1)
                            .addComponent(Y1)
                            .addComponent(Z1))
                        .addContainerGap())
                );

                setSize(new java.awt.Dimension(616, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        // TODO add your handling code here:
        A1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_A1MouseClicked

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        B1.setEnabled(false);  
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_B1MouseClicked

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        // TODO add your handling code here:
        C1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_C1MouseClicked

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseClicked
        // TODO add your handling code here:
        D1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_D1MouseClicked

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseClicked
        // TODO add your handling code here:
        E1.setEnabled(false);
        jLabel7.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel3.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_E1MouseClicked

    private void F1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F1MouseClicked
        // TODO add your handling code here:
        F1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_F1MouseClicked

    private void G1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G1MouseClicked
        // TODO add your handling code here:
        G1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_G1MouseClicked

    private void H1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H1MouseClicked
        // TODO add your handling code here:
        H1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_H1MouseClicked

    private void I1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_I1MouseClicked
        // TODO add your handling code here:
        I1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_I1MouseClicked

    private void J1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J1MouseClicked
        // TODO add your handling code here:
        J1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_J1MouseClicked

    private void K1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_K1MouseClicked
        // TODO add your handling code here:
        K1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_K1MouseClicked

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        // TODO add your handling code here:
        L1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_L1MouseClicked

    private void M1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M1MouseClicked
        // TODO add your handling code here:
        M1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_M1MouseClicked

    private void N1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MouseClicked
        // TODO add your handling code here:
        N1.setEnabled(false);
        jLabel3.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel3.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_N1MouseClicked

    private void O1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_O1MouseClicked
        // TODO add your handling code here:
        O1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_O1MouseClicked

    private void P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseClicked
        // TODO add your handling code here:
        P1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_P1MouseClicked

    private void Q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseClicked
        // TODO add your handling code here:
        Q1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_Q1MouseClicked

    private void R1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R1MouseClicked
        // TODO add your handling code here:
        R1.setEnabled(false);
        jLabel5.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel3.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_R1MouseClicked

    private void S1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S1MouseClicked
        // TODO add your handling code here:
        S1.setEnabled(false);
        jLabel6.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel3.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_S1MouseClicked

    private void T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MouseClicked
        // TODO add your handling code here:
        T1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_T1MouseClicked

    private void U1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U1MouseClicked
        // TODO add your handling code here:
        U1.setEnabled(false);
        jLabel4.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel3.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_U1MouseClicked

    private void V1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V1MouseClicked
        // TODO add your handling code here:
        V1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_V1MouseClicked

    private void W1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W1MouseClicked
        // TODO add your handling code here:
        W1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_W1MouseClicked

    private void X1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X1MouseClicked
        // TODO add your handling code here:
        X1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_X1MouseClicked

    private void Y1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Y1MouseClicked
        // TODO add your handling code here:
        Y1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_Y1MouseClicked

    private void Z1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Z1MouseClicked
        // TODO add your handling code here:
        Z1.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_Z1MouseClicked

    private void Skip1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Skip1
        // TODO add your handling code here:
        this.dispose();
        NewJFrame2 frame1 = new NewJFrame2();
        frame1.setVisible(true);
        frame1.jTextField1.setText(score + "");
    }//GEN-LAST:event_Skip1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton C1;
    private javax.swing.JToggleButton D1;
    private javax.swing.JToggleButton E1;
    private javax.swing.JToggleButton F1;
    private javax.swing.JToggleButton G1;
    private javax.swing.JToggleButton H1;
    private javax.swing.JToggleButton I1;
    private javax.swing.JToggleButton J1;
    private javax.swing.JToggleButton K1;
    private javax.swing.JToggleButton L1;
    private javax.swing.JToggleButton M1;
    private javax.swing.JToggleButton N1;
    private javax.swing.JLabel Nurse;
    private javax.swing.JToggleButton O1;
    private javax.swing.JToggleButton P1;
    private javax.swing.JToggleButton Q1;
    private javax.swing.JToggleButton R1;
    private javax.swing.JToggleButton S1;
    private javax.swing.JToggleButton T1;
    private javax.swing.JToggleButton U1;
    private javax.swing.JToggleButton V1;
    private javax.swing.JToggleButton W1;
    private javax.swing.JToggleButton X1;
    private javax.swing.JToggleButton Y1;
    private javax.swing.JToggleButton Z1;
    private javax.swing.JLabel chest;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lLeg;
    private javax.swing.JLabel left;
    private javax.swing.JLabel rLeg;
    private javax.swing.JLabel right;
    // End of variables declaration//GEN-END:variables
    private int score = 100;
    int timeRun = 0;
}
