/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/***************************************************************
* file: NewJFrame5.java
* author: A. Wang
* class: CS 245 Programming Graphical User Interfaces
*
* assignment: checkpoint 1.0
* date last modified: 8/9/2016
*
* purpose: This program creates the hangman game to be played with the answer
* pharmacy.
*
****************************************************************/ 
import java.util.Calendar;
import java.util.GregorianCalendar;
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("Score: " + score);
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lLeg = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        rLeg = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        chest = new javax.swing.JLabel();
        left = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jToggleButton1.setText("A");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jToggleButton2.setText("B");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        jToggleButton3.setText("C");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });

        jToggleButton4.setText("D");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });

        jToggleButton5.setText("E");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });

        jToggleButton6.setText("F");
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });

        jToggleButton7.setText("G");
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });

        jToggleButton8.setText("H");
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });

        jToggleButton9.setText("I");
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });

        jToggleButton10.setText("J");
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton10MouseClicked(evt);
            }
        });

        jToggleButton11.setText("K");
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton11MouseClicked(evt);
            }
        });

        jToggleButton12.setText("L");
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton12MouseClicked(evt);
            }
        });

        jToggleButton13.setText("M");
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton13MouseClicked(evt);
            }
        });

        jToggleButton14.setText("N");
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton14MouseClicked(evt);
            }
        });

        jToggleButton15.setText("O");
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton15MouseClicked(evt);
            }
        });

        jToggleButton16.setText("P");
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton16MouseClicked(evt);
            }
        });

        jToggleButton17.setText("Q");
        jToggleButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton17MouseClicked(evt);
            }
        });

        jToggleButton18.setText("R");
        jToggleButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton18MouseClicked(evt);
            }
        });

        jToggleButton19.setText("S");
        jToggleButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton19MouseClicked(evt);
            }
        });

        jToggleButton20.setText("T");
        jToggleButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton20MouseClicked(evt);
            }
        });

        jToggleButton21.setText("U");
        jToggleButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton21MouseClicked(evt);
            }
        });

        jToggleButton22.setText("V");
        jToggleButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton22MouseClicked(evt);
            }
        });

        jToggleButton23.setText("W");
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton23MouseClicked(evt);
            }
        });

        jToggleButton24.setText("X");
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton24MouseClicked(evt);
            }
        });

        jToggleButton25.setText("Y");
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton25MouseClicked(evt);
            }
        });

        jToggleButton26.setText("Z");
        jToggleButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton26MouseClicked(evt);
            }
        });

        jButton1.setText("Skip");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Skip(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Alibi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Hangman");

        jLabel3.setText("___    ___    ___    ___    ___    ___    ___    ___");

        jTextField1.setFocusable(false);

        jTextField2.setFocusable(false);
        new Thread(){
            public void run(){
                while (timeRun == 0){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    String time = month+1 + "/" + day + "/" + year + " " + hour + ":" + min + ":" + sec + " ";
                    jTextField2.setText(time);
                }
            }
        }.start();

        jLabel4.setText("  p  ");
        jLabel4.setToolTipText("");
        jLabel4.setVisible(false);

        jLabel5.setText("  h  ");
        jLabel5.setVisible(false);

        jLabel6.setText("  a  ");
        jLabel6.setVisible(false);

        jLabel7.setText("  r  ");
        jLabel7.setVisible(false);

        jLabel8.setText("  m  ");
        jLabel8.setVisible(false);

        jLabel9.setText("  a  ");
        jLabel9.setVisible(false);

        jLabel10.setText("  c  ");
        jLabel10.setVisible(false);

        jLabel11.setText("  y  ");
        jLabel11.setVisible(false);

        lLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLeg.setText("/");
        lLeg.setVisible(false);

        right.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        right.setText("\\");
            right.setVisible(false);

            rLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            rLeg.setText("\\");
                rLeg.setVisible(false);

                head.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
                head.setText("O");
                head.setVisible(false);

                chest.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
                chest.setText(" l");
                chest.setVisible(false);

                left.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                left.setText("/");
                left.setVisible(false);

                jLayeredPane1.setLayer(lLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(right, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(rLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(head, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(chest, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(left, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
                jLayeredPane1.setLayout(jLayeredPane1Layout);
                jLayeredPane1Layout.setHorizontalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rLeg))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(head)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(right)))
                        .addContainerGap())
                );
                jLayeredPane1Layout.setVerticalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(head)
                        .addGap(1, 1, 1)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chest)
                            .addComponent(right)
                            .addComponent(left))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLeg)
                            .addComponent(rLeg))
                        .addContainerGap())
                );

                jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel12.setText("|");

                jLabel13.setText("_____________");

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jToggleButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jToggleButton13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel12))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel10)
                                                        .addGap(14, 14, 14)
                                                        .addComponent(jLabel11)))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton2)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton4)
                            .addComponent(jToggleButton5)
                            .addComponent(jToggleButton6)
                            .addComponent(jToggleButton7)
                            .addComponent(jToggleButton8)
                            .addComponent(jToggleButton9)
                            .addComponent(jToggleButton10)
                            .addComponent(jToggleButton11)
                            .addComponent(jToggleButton12)
                            .addComponent(jToggleButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton14)
                            .addComponent(jToggleButton15)
                            .addComponent(jToggleButton16)
                            .addComponent(jToggleButton17)
                            .addComponent(jToggleButton18)
                            .addComponent(jToggleButton19)
                            .addComponent(jToggleButton20)
                            .addComponent(jToggleButton21)
                            .addComponent(jToggleButton22)
                            .addComponent(jToggleButton23)
                            .addComponent(jToggleButton24)
                            .addComponent(jToggleButton25)
                            .addComponent(jToggleButton26))
                        .addContainerGap())
                );

                setSize(new java.awt.Dimension(616, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        jToggleButton1.setEnabled(false);
        jLabel6.setVisible(true);
        jLabel9.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        // TODO add your handling code here:
        jToggleButton2.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        // TODO add your handling code here:
        jToggleButton3.setEnabled(false);
        jLabel10.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        // TODO add your handling code here:
        jToggleButton4.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        // TODO add your handling code here:
        jToggleButton5.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        // TODO add your handling code here:
        jToggleButton6.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        // TODO add your handling code here:
        jToggleButton7.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        // TODO add your handling code here:
        jToggleButton8.setEnabled(false);
        jLabel5.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
            && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
            && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        // TODO add your handling code here:
        jToggleButton9.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton9MouseClicked

    private void jToggleButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton10MouseClicked
        // TODO add your handling code here:
        jToggleButton10.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton10MouseClicked

    private void jToggleButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton11MouseClicked
        // TODO add your handling code here:
        jToggleButton11.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton11MouseClicked

    private void jToggleButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton12MouseClicked
        // TODO add your handling code here:
        jToggleButton12.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton12MouseClicked

    private void jToggleButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton13MouseClicked
        // TODO add your handling code here:
        jToggleButton13.setEnabled(false);
        jLabel8.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton13MouseClicked

    private void jToggleButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton14MouseClicked
        // TODO add your handling code here:
        jToggleButton14.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton14MouseClicked

    private void jToggleButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton15MouseClicked
        // TODO add your handling code here:
        jToggleButton15.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton15MouseClicked

    private void jToggleButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton16MouseClicked
        // TODO add your handling code here:
        jToggleButton16.setEnabled(false);
        jLabel4.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton16MouseClicked

    private void jToggleButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton17MouseClicked
        // TODO add your handling code here:
        jToggleButton17.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton17MouseClicked

    private void jToggleButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton18MouseClicked
        // TODO add your handling code here:
        jToggleButton18.setEnabled(false);
        jLabel7.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton18MouseClicked

    private void jToggleButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton19MouseClicked
        // TODO add your handling code here:
        jToggleButton19.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton19MouseClicked

    private void jToggleButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton20MouseClicked
        // TODO add your handling code here:
        jToggleButton20.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton20MouseClicked

    private void jToggleButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton21MouseClicked
        // TODO add your handling code here:
        jToggleButton21.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton21MouseClicked

    private void jToggleButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton22MouseClicked
        // TODO add your handling code here:
        jToggleButton22.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton22MouseClicked

    private void jToggleButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MouseClicked
        // TODO add your handling code here:
        jToggleButton23.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton23MouseClicked

    private void jToggleButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton24MouseClicked
        // TODO add your handling code here:
        jToggleButton24.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton24MouseClicked

    private void jToggleButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton25MouseClicked
        // TODO add your handling code here:
        jToggleButton25.setEnabled(false);
        jLabel11.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton25MouseClicked

    private void jToggleButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton26MouseClicked
        // TODO add your handling code here:
        jToggleButton26.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton26MouseClicked

    private void Skip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Skip
        // TODO add your handling code here:
        this.dispose();
        NewJFrame2 frame1 = new NewJFrame2();
        frame1.setVisible(true);
        frame1.jTextField1.setText(score + "");
    }//GEN-LAST:event_Skip

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chest;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lLeg;
    private javax.swing.JLabel left;
    private javax.swing.JLabel rLeg;
    private javax.swing.JLabel right;
    // End of variables declaration//GEN-END:variables
    int score = 100;
    int timeRun = 0;
}
