/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/***************************************************************
* file: NewJFrame6.java
* author: A. Wang
* class: CS 245 Programming Graphical User Interfaces
*
* assignment: checkpoint 1.0
* date last modified: 8/9/2016
*
* purpose: This program creates the hangman game to be played with the answer
* climbing.
*
****************************************************************/ 
import java.util.Calendar;
import java.util.GregorianCalendar;
public class NewJFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        a = new javax.swing.JToggleButton();
        b = new javax.swing.JToggleButton();
        c = new javax.swing.JToggleButton();
        d = new javax.swing.JToggleButton();
        e = new javax.swing.JToggleButton();
        f = new javax.swing.JToggleButton();
        g = new javax.swing.JToggleButton();
        h = new javax.swing.JToggleButton();
        i = new javax.swing.JToggleButton();
        j = new javax.swing.JToggleButton();
        k = new javax.swing.JToggleButton();
        l = new javax.swing.JToggleButton();
        m = new javax.swing.JToggleButton();
        n = new javax.swing.JToggleButton();
        o = new javax.swing.JToggleButton();
        p = new javax.swing.JToggleButton();
        q = new javax.swing.JToggleButton();
        r = new javax.swing.JToggleButton();
        s = new javax.swing.JToggleButton();
        t = new javax.swing.JToggleButton();
        u = new javax.swing.JToggleButton();
        v = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("Score: " + score);
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lLeg = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        rLeg = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        chest = new javax.swing.JLabel();
        left = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        a.setText("A");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });

        b.setText("B");
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });

        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });

        d.setText("D");
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
        });

        e.setText("E");
        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eMouseClicked(evt);
            }
        });

        f.setText("F");
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fMouseClicked(evt);
            }
        });

        g.setText("G");
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gMouseClicked(evt);
            }
        });

        h.setText("H");
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hMouseClicked(evt);
            }
        });

        i.setText("I");
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMouseClicked(evt);
            }
        });

        j.setText("J");
        j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMouseClicked(evt);
            }
        });

        k.setText("K");
        k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kMouseClicked(evt);
            }
        });

        l.setText("L");
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMouseClicked(evt);
            }
        });

        m.setText("M");
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMouseClicked(evt);
            }
        });

        n.setText("N");
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMouseClicked(evt);
            }
        });

        o.setText("O");
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oMouseClicked(evt);
            }
        });

        p.setText("P");
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMouseClicked(evt);
            }
        });

        q.setText("Q");
        q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qMouseClicked(evt);
            }
        });

        r.setText("R");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rMouseClicked(evt);
            }
        });

        s.setText("S");
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMouseClicked(evt);
            }
        });

        t.setText("T");
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });

        u.setText("U");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });

        v.setText("V");
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMouseClicked(evt);
            }
        });

        jToggleButton23.setText("W");
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton23MouseClicked(evt);
            }
        });

        jToggleButton24.setText("X");
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton24MouseClicked(evt);
            }
        });

        jToggleButton25.setText("Y");
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton25MouseClicked(evt);
            }
        });

        jToggleButton26.setText("Z");
        jToggleButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton26MouseClicked(evt);
            }
        });

        jButton1.setText("Skip");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skip(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Alibi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Hangman");

        jLabel3.setText("___    ___    ___    ___    ___    ___    ___    ___");

        jTextField1.setFocusable(false);

        jTextField2.setFocusable(false);
        new Thread(){
            public void run(){
                while (timeRun == 0){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    String time = month+1 + "/" + day + "/" + year + " " + hour + ":" + min + ":" + sec + " ";
                    jTextField2.setText(time);
                }
            }
        }.start();

        jLabel4.setText("  c  ");
        jLabel4.setVisible(false);

        jLabel5.setText("  l  ");
        jLabel5.setVisible(false);

        jLabel6.setText("  i  ");
        jLabel6.setVisible(false);

        jLabel7.setText("  m  ");
        jLabel7.setVisible(false);

        jLabel8.setText("  b  ");
        jLabel8.setVisible(false);

        jLabel9.setText("  i  ");
        jLabel9.setVisible(false);

        jLabel10.setText("  n  ");
        jLabel10.setVisible(false);

        jLabel11.setText("  g  ");
        jLabel11.setVisible(false);

        lLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLeg.setText("/");
        lLeg.setVisible(false);

        right.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        right.setText("\\");
            right.setVisible(false);

            rLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            rLeg.setText("\\");
                rLeg.setVisible(false);

                head.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
                head.setText("O");
                head.setVisible(false);

                chest.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
                chest.setText(" l");
                chest.setVisible(false);

                left.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                left.setText("/");
                left.setVisible(false);

                jLayeredPane1.setLayer(lLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(right, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(rLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(head, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(chest, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(left, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
                jLayeredPane1.setLayout(jLayeredPane1Layout);
                jLayeredPane1Layout.setHorizontalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rLeg))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(head)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(right)))
                        .addContainerGap())
                );
                jLayeredPane1Layout.setVerticalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(head)
                        .addGap(1, 1, 1)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chest)
                            .addComponent(right)
                            .addComponent(left))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLeg)
                            .addComponent(rLeg))
                        .addContainerGap())
                );

                jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel12.setText("|");

                jLabel13.setText("_____________");

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(o)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(u)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton26)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(e)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(f)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(g)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(h)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(i)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(j)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(k)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(l)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(m))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel9)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel11))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(16, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1))
                                        .addGap(24, 24, 24))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addGap(219, 219, 219))))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel1))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(b)
                            .addComponent(c)
                            .addComponent(d)
                            .addComponent(e)
                            .addComponent(f)
                            .addComponent(g)
                            .addComponent(h)
                            .addComponent(i)
                            .addComponent(j)
                            .addComponent(k)
                            .addComponent(l)
                            .addComponent(m))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n)
                            .addComponent(o)
                            .addComponent(p)
                            .addComponent(q)
                            .addComponent(r)
                            .addComponent(s)
                            .addComponent(t)
                            .addComponent(u)
                            .addComponent(v)
                            .addComponent(jToggleButton23)
                            .addComponent(jToggleButton24)
                            .addComponent(jToggleButton25)
                            .addComponent(jToggleButton26))
                        .addContainerGap())
                );

                setSize(new java.awt.Dimension(616, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        // TODO add your handling code here:
        a.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_aMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        // TODO add your handling code here:
        b.setEnabled(false);
        jLabel8.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_bMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        // TODO add your handling code here:
        c.setEnabled(false);
        jLabel4.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_cMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        // TODO add your handling code here:
        d.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_dMouseClicked

    private void eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseClicked
        // TODO add your handling code here:
        e.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_eMouseClicked

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        // TODO add your handling code here:
        f.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_fMouseClicked

    private void gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseClicked
        // TODO add your handling code here:
        g.setEnabled(false);
        jLabel11.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_gMouseClicked

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked
        // TODO add your handling code here:
        h.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_hMouseClicked

    private void iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseClicked
        // TODO add your handling code here:
        i.setEnabled(false);
        jLabel6.setVisible(true);
        jLabel9.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_iMouseClicked

    private void jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMouseClicked
        // TODO add your handling code here:
        j.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jMouseClicked

    private void kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kMouseClicked
        // TODO add your handling code here:
        k.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_kMouseClicked

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked
        // TODO add your handling code here:
        l.setEnabled(false);
        jLabel5.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_lMouseClicked

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
        // TODO add your handling code here:
        m.setEnabled(false);
        jLabel7.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_mMouseClicked

    private void nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseClicked
        // TODO add your handling code here:
        n.setEnabled(false);
        jLabel10.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_nMouseClicked

    private void oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseClicked
        // TODO add your handling code here:
        o.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_oMouseClicked

    private void pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseClicked
        // TODO add your handling code here:
        p.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_pMouseClicked

    private void qMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qMouseClicked
        // TODO add your handling code here:
        q.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_qMouseClicked

    private void rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseClicked
        // TODO add your handling code here:
        r.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_rMouseClicked

    private void sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseClicked
        // TODO add your handling code here:
        s.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_sMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        t.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_tMouseClicked

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
        // TODO add your handling code here:
        u.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_uMouseClicked

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
        // TODO add your handling code here:
        v.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_vMouseClicked

    private void jToggleButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MouseClicked
        // TODO add your handling code here:
        jToggleButton23.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton23MouseClicked

    private void jToggleButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton24MouseClicked
        // TODO add your handling code here:
        jToggleButton24.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton24MouseClicked

    private void jToggleButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton25MouseClicked
        // TODO add your handling code here:
        jToggleButton25.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton25MouseClicked

    private void jToggleButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton26MouseClicked
        // TODO add your handling code here:
        jToggleButton26.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton26MouseClicked

    private void skip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skip
        // TODO add your handling code here:
        this.dispose();
        NewJFrame2 frame1 = new NewJFrame2();
        frame1.setVisible(true);
        frame1.jTextField1.setText(score + "");
    }//GEN-LAST:event_skip

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton a;
    private javax.swing.JToggleButton b;
    private javax.swing.JToggleButton c;
    private javax.swing.JLabel chest;
    private javax.swing.JToggleButton d;
    private javax.swing.JToggleButton e;
    private javax.swing.JToggleButton f;
    private javax.swing.JToggleButton g;
    private javax.swing.JToggleButton h;
    private javax.swing.JLabel head;
    private javax.swing.JToggleButton i;
    private javax.swing.JToggleButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton k;
    private javax.swing.JToggleButton l;
    private javax.swing.JLabel lLeg;
    private javax.swing.JLabel left;
    private javax.swing.JToggleButton m;
    private javax.swing.JToggleButton n;
    private javax.swing.JToggleButton o;
    private javax.swing.JToggleButton p;
    private javax.swing.JToggleButton q;
    private javax.swing.JToggleButton r;
    private javax.swing.JLabel rLeg;
    private javax.swing.JLabel right;
    private javax.swing.JToggleButton s;
    private javax.swing.JToggleButton t;
    private javax.swing.JToggleButton u;
    private javax.swing.JToggleButton v;
    // End of variables declaration//GEN-END:variables
    private int score = 100;
    private int timeRun = 0;
}
