/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/***************************************************************
* file: NewJFrame3.java
* author: A. Wang
* class: CS 245 Programming Graphical User Interfaces
*
* assignment: checkpoint 1.0
* date last modified: 8/9/2016
*
* purpose: This program creates the hangman game to be played with the answer
* abstract.
*
****************************************************************/ 
import java.util.Calendar;
import java.util.GregorianCalendar;
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        A = new javax.swing.JToggleButton();
        B = new javax.swing.JToggleButton();
        C = new javax.swing.JToggleButton();
        D = new javax.swing.JToggleButton();
        E = new javax.swing.JToggleButton();
        F = new javax.swing.JToggleButton();
        G = new javax.swing.JToggleButton();
        H = new javax.swing.JToggleButton();
        I = new javax.swing.JToggleButton();
        J = new javax.swing.JToggleButton();
        K = new javax.swing.JToggleButton();
        L = new javax.swing.JToggleButton();
        M = new javax.swing.JToggleButton();
        N = new javax.swing.JToggleButton();
        O = new javax.swing.JToggleButton();
        P = new javax.swing.JToggleButton();
        Q = new javax.swing.JToggleButton();
        R = new javax.swing.JToggleButton();
        S = new javax.swing.JToggleButton();
        t = new javax.swing.JToggleButton();
        u = new javax.swing.JToggleButton();
        v = new javax.swing.JToggleButton();
        w = new javax.swing.JToggleButton();
        x = new javax.swing.JToggleButton();
        y = new javax.swing.JToggleButton();
        z = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setText("Score: " + score);
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lLeg = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        rLeg = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        chest = new javax.swing.JLabel();
        left = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        A.setText("A");
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });

        B.setText("B");
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
        });

        C.setText("C");
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });

        D.setText("D");
        D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DMouseClicked(evt);
            }
        });

        E.setText("E");
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
        });

        F.setText("F");
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });

        G.setText("G");
        G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GMouseClicked(evt);
            }
        });

        H.setText("H");
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HMouseClicked(evt);
            }
        });

        I.setText("I");
        I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMouseClicked(evt);
            }
        });

        J.setText("J");
        J.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMouseClicked(evt);
            }
        });

        K.setText("K");
        K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KMouseClicked(evt);
            }
        });

        L.setText("L");
        L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMouseClicked(evt);
            }
        });

        M.setText("M");
        M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMouseClicked(evt);
            }
        });

        N.setText("N");
        N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMouseClicked(evt);
            }
        });

        O.setText("O");
        O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMouseClicked(evt);
            }
        });

        P.setText("P");
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMouseClicked(evt);
            }
        });

        Q.setText("Q");
        Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QMouseClicked(evt);
            }
        });

        R.setText("R");
        R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMouseClicked(evt);
            }
        });

        S.setText("S");
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
        });

        t.setText("T");
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });

        u.setText("U");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });

        v.setText("V");
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMouseClicked(evt);
            }
        });

        w.setText("W");
        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wMouseClicked(evt);
            }
        });

        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });

        y.setText("Y");
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yMouseClicked(evt);
            }
        });

        z.setText("Z");
        z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zMouseClicked(evt);
            }
        });

        jButton1.setText("Skip");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Skip2(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Alibi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Hangman");

        jLabel3.setText("___    ___    ___    ___    ___    ___    ___    ___");

        jTextField1.setFocusable(false);

        jTextField2.setFocusable(false);
        new Thread(){
            public void run(){
                while (timeRun == 0){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    String time = month+1 + "/" + day + "/" + year + " " + hour + ":" + min + ":" + sec + " ";
                    jTextField2.setText(time);
                }
            }
        }.start();

        jLabel4.setText("  a  ");
        jLabel4.setOpaque(true);
        jLabel4.setVisible(false);

        jLabel5.setText("  b  ");
        jLabel5.setVisible(false);

        jLabel6.setText("  s  ");
        jLabel6.setVisible(false);

        jLabel7.setText("  t  ");
        jLabel7.setVisible(false);

        jLabel8.setText("  r  ");
        jLabel8.setVisible(false);

        jLabel9.setText("  a  ");
        jLabel9.setOpaque(true);
        jLabel9.setVisible(false);

        jLabel10.setText("  c  ");
        jLabel10.setToolTipText("");
        jLabel10.setVisible(false);

        jLabel11.setText("  t  ");
        jLabel11.setVisible(false);

        lLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLeg.setText("/");
        lLeg.setVisible(false);

        right.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        right.setText("\\");
            right.setVisible(false);

            rLeg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            rLeg.setText("\\");
                rLeg.setVisible(false);

                head.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
                head.setText("O");
                head.setVisible(false);

                chest.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
                chest.setText(" l");
                chest.setVisible(false);

                left.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                left.setText("/");
                left.setVisible(false);

                jLayeredPane1.setLayer(lLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(right, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(rLeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(head, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(chest, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jLayeredPane1.setLayer(left, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
                jLayeredPane1.setLayout(jLayeredPane1Layout);
                jLayeredPane1Layout.setHorizontalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rLeg))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(head)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(right)))
                        .addContainerGap())
                );
                jLayeredPane1Layout.setVerticalGroup(
                    jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(head)
                        .addGap(1, 1, 1)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chest)
                            .addComponent(right)
                            .addComponent(left))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLeg)
                            .addComponent(rLeg))
                        .addContainerGap())
                );

                jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel12.setText("|");

                jLabel13.setText("_____________");

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(N)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(O)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(P)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Q)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(R)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(S)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(u)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(v)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(w)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(x)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(y)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(z))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(F)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(I)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(J)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(K)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(M))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A)
                            .addComponent(B)
                            .addComponent(C)
                            .addComponent(D)
                            .addComponent(E)
                            .addComponent(F)
                            .addComponent(G)
                            .addComponent(H)
                            .addComponent(I)
                            .addComponent(J)
                            .addComponent(K)
                            .addComponent(L)
                            .addComponent(M))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(N)
                            .addComponent(O)
                            .addComponent(P)
                            .addComponent(Q)
                            .addComponent(R)
                            .addComponent(S)
                            .addComponent(t)
                            .addComponent(u)
                            .addComponent(v)
                            .addComponent(w)
                            .addComponent(x)
                            .addComponent(y)
                            .addComponent(z))
                        .addContainerGap())
                );

                setSize(new java.awt.Dimension(616, 438));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        // TODO add your handling code here:
        A.setEnabled(false);
        jLabel4.setVisible(true);
        jLabel9.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_AMouseClicked

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
        // TODO add your handling code here:
        B.setEnabled(false);
        jLabel5.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_BMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
        // TODO add your handling code here:
        C.setEnabled(false);
        jLabel10.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_CMouseClicked

    private void DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseClicked
        // TODO add your handling code here:
        D.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_DMouseClicked

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
        // TODO add your handling code here:
        E.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_EMouseClicked

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
        // TODO add your handling code here:
        F.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_FMouseClicked

    private void GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMouseClicked
        // TODO add your handling code here:
        G.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_GMouseClicked

    private void HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseClicked
        // TODO add your handling code here:
        H.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_HMouseClicked

    private void IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMouseClicked
        // TODO add your handling code here:
        I.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_IMouseClicked

    private void JMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMouseClicked
        // TODO add your handling code here:
        J.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_JMouseClicked

    private void KMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseClicked
        // TODO add your handling code here:
        K.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_KMouseClicked

    private void LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMouseClicked
        // TODO add your handling code here:
        L.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_LMouseClicked

    private void MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseClicked
        // TODO add your handling code here:
        M.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_MMouseClicked

    private void NMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseClicked
        // TODO add your handling code here:
        N.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_NMouseClicked

    private void OMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseClicked
        // TODO add your handling code here:
        O.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_OMouseClicked

    private void PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseClicked
        // TODO add your handling code here:
        P.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_PMouseClicked

    private void QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QMouseClicked
        // TODO add your handling code here:
        Q.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_QMouseClicked

    private void RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMouseClicked
        // TODO add your handling code here:
        R.setEnabled(false);
        jLabel8.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_RMouseClicked

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked
        // TODO add your handling code here:
        S.setEnabled(false);
        jLabel6.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_SMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        t.setEnabled(false);
        jLabel7.setVisible(true);
        jLabel11.setVisible(true);
        if (jLabel4.isVisible() && jLabel5.isVisible() && jLabel6.isVisible()
                && jLabel7.isVisible() && jLabel8.isVisible() && jLabel9.isVisible()
                && jLabel10.isVisible() && jLabel11.isVisible()){

            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_tMouseClicked

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
        // TODO add your handling code here:
        u.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_uMouseClicked

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
        // TODO add your handling code here:
        v.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_vMouseClicked

    private void wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wMouseClicked
        // TODO add your handling code here:
        w.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_wMouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
        x.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_xMouseClicked

    private void yMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseClicked
        // TODO add your handling code here:
        y.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_yMouseClicked

    private void zMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zMouseClicked
        // TODO add your handling code here:
        z.setEnabled(false);
        score = score - 10;
        jTextField1.setText("Score: " + score);
        if (head.isVisible() == false)
            head.setVisible(true);
        else if (chest.isVisible() == false)
            chest.setVisible(true);
        else if (right.isVisible() == false)
            right.setVisible(true);
        else if (left.isVisible() == false)
            left.setVisible(true);
        else if (lLeg.isVisible() == false)
            lLeg.setVisible(true);
        else if (rLeg.isVisible() == false){
            rLeg.setVisible(true);
            this.dispose();
            NewJFrame2 frame1 = new NewJFrame2();
            frame1.setVisible(true);
        }
    }//GEN-LAST:event_zMouseClicked

    private void Skip2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Skip2
        // TODO add your handling code here:
        this.dispose();
        NewJFrame2 frame1 = new NewJFrame2();
        frame1.setVisible(true);
        frame1.jTextField1.setText(score + "");
    }//GEN-LAST:event_Skip2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A;
    private javax.swing.JToggleButton B;
    private javax.swing.JToggleButton C;
    private javax.swing.JToggleButton D;
    private javax.swing.JToggleButton E;
    private javax.swing.JToggleButton F;
    private javax.swing.JToggleButton G;
    private javax.swing.JToggleButton H;
    private javax.swing.JToggleButton I;
    private javax.swing.JToggleButton J;
    private javax.swing.JToggleButton K;
    private javax.swing.JToggleButton L;
    private javax.swing.JToggleButton M;
    private javax.swing.JToggleButton N;
    private javax.swing.JToggleButton O;
    private javax.swing.JToggleButton P;
    private javax.swing.JToggleButton Q;
    private javax.swing.JToggleButton R;
    private javax.swing.JToggleButton S;
    private javax.swing.JLabel chest;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lLeg;
    private javax.swing.JLabel left;
    private javax.swing.JLabel rLeg;
    private javax.swing.JLabel right;
    private javax.swing.JToggleButton t;
    private javax.swing.JToggleButton u;
    private javax.swing.JToggleButton v;
    private javax.swing.JToggleButton w;
    private javax.swing.JToggleButton x;
    private javax.swing.JToggleButton y;
    private javax.swing.JToggleButton z;
    // End of variables declaration//GEN-END:variables
    private int score = 100;
    int timeRun = 0;
}
